# Generated by Django 4.2.4 on 2024-07-26 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deepdive", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="database",
            name="user",
        ),
        migrations.RemoveField(
            model_name="databasefile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="session",
            name="user",
        ),
    ]
